In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6,7])

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(7,)

In [6]:
a.dtype

dtype('int64')

In [8]:
a=np.array([[1,2,3,4],[5,6,7,8]])

In [9]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
a.shape

(2, 4)

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
np.ones((3,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [14]:
np.zeros((2,5),dtype='int64')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
arr=np.array([[1,2,3],[4,5,6]])

In [16]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [18]:
5*arr

array([[ 5, 10, 15],
       [20, 25, 30]])

In [19]:
arr/arr

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [20]:
arr/2

array([[ 0.5,  1. ,  1.5],
       [ 2. ,  2.5,  3. ]])

In [21]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [22]:
arr+arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [23]:
arr+5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [25]:
3-arr

array([[ 2,  1,  0],
       [-1, -2, -3]])

In [26]:
arr**3

array([[  1,   8,  27],
       [ 64, 125, 216]])

In [27]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[5]

5

In [29]:
arr[2:9]

array([2, 3, 4, 5, 6, 7, 8])

In [30]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr[2]

array([7, 8, 9])

In [32]:
arr[1][2]

6

In [33]:
arr[1,2]

6

In [34]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,2]]])

In [35]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 2]]])

In [36]:
arr[0,1]

array([4, 5, 6])

In [37]:
arr[1,0,2]

9

In [38]:
arr=np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [40]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [42]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [43]:
A=np.random.randn(10)
A

array([-0.80892934,  0.085725  , -1.04794508,  1.46228374,  1.07797087,
       -0.20861931, -0.59023268,  1.0834886 , -1.76437486, -0.86786202])

In [44]:
A

array([-0.80892934,  0.085725  , -1.04794508,  1.46228374,  1.07797087,
       -0.20861931, -0.59023268,  1.0834886 , -1.76437486, -0.86786202])

In [45]:
A=np.random.randn(10)
A

array([-1.17798763, -0.07603074,  1.19767248,  0.79467248,  1.00431447,
       -0.17817296, -0.44992835, -0.7940521 ,  1.37140833, -0.30920489])

In [46]:
np.sign(A)

array([-1., -1.,  1.,  1.,  1., -1., -1., -1.,  1., -1.])

In [47]:
tmp = np.array([ 0.54090848,  0.70922084,  0.57458547,  0.55307476,  0.738459  ])

In [48]:
tmp.mean()

0.62324970999999996

In [50]:
tmp.std()

0.083351095632839739