In [1]:
import numpy as np

In [2]:
measure=np.array([
    [170,65,20],
    [180,80,25],
    [160,55,15]
    ])

In [3]:
print(measure)

[[170  65  20]
 [180  80  25]
 [160  55  15]]


In [4]:
A = np.array([
        [1,0,0],
        [0,1,0],
        [0,1,0],
        [0,0,1]
    ])

B = np.array([
        [158,50,84,63,86]
    ])

C = np.array([
        [1],
        [2],
        [0],
        [2],
        [0]
    ])

In [5]:
print(A,end='\n\n')
print(B,end='\n\n')
print(C)

[[1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]]

[[158  50  84  63  86]]

[[1]
 [2]
 [0]
 [2]
 [0]]


In [6]:
print("A.shape = " + str(A.shape)) 
print("B.shape = " + str(B.shape))
print("C.shape = " + str(C.shape)) 

A.shape = (4, 3)
B.shape = (1, 5)
C.shape = (5, 1)


In [7]:
print(measure)

[[170  65  20]
 [180  80  25]
 [160  55  15]]


In [8]:
measure[1,2]

25

In [9]:
print(measure)

[[170  65  20]
 [180  80  25]
 [160  55  15]]


In [10]:
print(measure[0,:])
print(measure[0,:].shape)

[170  65  20]
(3,)


In [11]:
print(measure[0,:].reshape(1,-1))
print(measure[0,:].reshape(1,-1).shape)

[[170  65  20]]
(1, 3)


In [13]:
print(measure[:,1])
print(measure[:,1].shape)

[65 80 55]
(3,)


In [14]:
print(measure[:,1].reshape(-1,1))
print(measure[:,1].reshape(-1,1).shape)

[[65]
 [80]
 [55]]
(3, 1)


In [15]:
print(measure)

[[170  65  20]
 [180  80  25]
 [160  55  15]]


In [16]:
print(measure.T)

[[170 180 160]
 [ 65  80  55]
 [ 20  25  15]]


In [17]:
D=np.array([
    [10,30],
    [20,40],
])
F=np.array([
    [1,2],
    [3,4],
])

In [18]:
print(D+F)

[[11 32]
 [23 44]]


In [19]:
print(D-F)

[[ 9 28]
 [17 36]]


In [20]:
a=np.array([[1,2,3]])
b=np.array([[4,5,6]])
c=np.array([
    [1],
    [2],
    [3],
])
d=np.array([
    [4],
    [5],
    [6],
])

In [21]:
print(a+b)
print(c+d)

[[5 7 9]]
[[5]
 [7]
 [9]]


In [22]:
print(a-b)
print(c-d)

[[-3 -3 -3]]
[[-3]
 [-3]
 [-3]]


In [24]:
G=np.array([
    [1,2],
    [3,4],
])

In [25]:
print(10*G)

[[10 20]
 [30 40]]


In [26]:
a = np.array([[1, 2, 3]])
c = np.array([
        [1],
        [2],
        [3]
    ])

In [27]:
print(10 * a)
print(10 * c)

[[10 20 30]]
[[10]
 [20]
 [30]]


In [28]:
J = np.array([
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ])

K = np.array([
        [10, 20],
        [30, 40],
        [50, 60],
        [70, 80]
    ])

In [30]:
print(np.dot(J,K))

[[ 500  600]
 [1140 1400]
 [1780 2200]]


In [31]:
print(J@K)

[[ 500  600]
 [1140 1400]
 [1780 2200]]


In [33]:
print(D*F)

[[ 10  60]
 [ 60 160]]


In [34]:
print(D @ F)
print(F @ D)

[[100 140]
 [140 200]]
[[ 50 110]
 [110 250]]


In [35]:
e = np.array([
        [1],
        [2],
        [3],
        [4]
    ])

f = np.array([
        [10],
        [20],
        [30],
        [40]
    ])

In [36]:
print(np.dot(e.T,f))

[[300]]


In [38]:
print(e.T@f)

[[300]]


In [39]:
A=np.array([
    [220,100],
    [150,150]
])
X=np.array([
    [2],
    [3]
])

In [40]:
print(A@X)

[[740]
 [750]]
